# Generated by Django 5.0.2 on 2024-03-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currentZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('block_lot', models.CharField(blank=True, max_length=100, null=True)),
                ('arms_length', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.CharField(blank=True, max_length=100, null=True)),
                ('building_class', models.CharField(blank=True, max_length=100, null=True)),
                ('building_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('building_sqft', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_sqft', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('zoning_districts', models.CharField(blank=True, max_length=100, null=True)),
                ('far_as_built', models.CharField(blank=True, max_length=100, null=True)),
                ('special_factors', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('called', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, default='unknown', max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='scraper.ownerdata')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousFilings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('filing_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_filings', to='scraper.propertydata')),
            ],
        ),
        migrations.AddField(
            model_name='ownerdata',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='scraper.propertydata'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('event', models.CharField(blank=True, choices=[('follow_up_call', 'follow up call'), ('reschedule_appointment', 'reschedule appointment'), ('needs_visit', 'needs visit'), ('property_appointment_scheduled', 'property appointment scheduled'), ('contract_signing', 'contract signing'), ('scheduled_appraisal', 'scheduled appraisal'), ('scheduled_inspection', 'scheduled inspection'), ('scheduled_cash_for_keys_negotiation', 'scheduled cash for keys negotiation'), ('scheduled_closing', 'scheduled closing')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scraper.ownerdata')),
                ('on_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scraper.propertydata')),
            ],
        ),
        migrations.CreateModel(
            name='TruePeopleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('data_found', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_people_data', to='scraper.ownerdata')),
            ],
        ),
    ]
