# Generated by Django 5.0.2 on 2024-02-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('block_lot', models.CharField(blank=True, max_length=100, null=True)),
                ('arms_length', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('building_class', models.CharField(blank=True, max_length=100, null=True)),
                ('building_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('building_sqft', models.IntegerField(blank=True, null=True)),
                ('lot_sqft', models.IntegerField(blank=True, null=True)),
                ('lot_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('zoning_districts', models.CharField(blank=True, max_length=100, null=True)),
                ('far_as_built', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('special_factors', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousFilings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField()),
                ('filing_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_filings', to='scraper.propertydata')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='scraper.propertydata')),
            ],
        ),
    ]
