# Generated by Django 5.0.2 on 2024-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_truepeopledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
