# Generated by Django 5.0.2 on 2024-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_propertydata_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
