# Generated by Django 5.0.2 on 2024-02-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_propertydata_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='city',
            field=models.CharField(default='far rockaway', max_length=100),
            preserve_default=False,
        ),
    ]
