# Generated by Django 5.0.2 on 2024-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_propertydata_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
