# Generated by Django 5.0.2 on 2024-02-18 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_event_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scraper.ownerdata'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(blank=True, choices=[('option1', 'follow up call'), ('option2', 'reschedule appointment'), ('option3', 'needs visit'), ('option4', 'property appointment scheduled'), ('option5', 'contract signing'), ('option6', 'scheduled appraisle'), ('option7', 'scheduled inspection'), ('option8', 'scheduled cash for keys negotiation'), ('option9', 'scheduled closing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='on_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scraper.propertydata'),
        ),
    ]
