# Generated by Django 5.0.2 on 2024-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_alter_event_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
