# Generated by Django 5.0.2 on 2024-02-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_remove_ownerdata_phone_number_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
