# Generated by Django 5.0.2 on 2024-02-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_phonenumber_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='truepeopledata',
            name='data_found',
            field=models.BooleanField(default=False),
        ),
    ]
