# Generated by Django 5.0.2 on 2024-02-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_event_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
