# Generated by Django 5.0.2 on 2024-02-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_currentzip'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
